---
- name: Create directory for clients configuration
  file:
    path: "{{ openvpn_client_dir }}"
    state: directory
    owner: root
    group: remote
    mode: 0775

- name: Copy OpenVPN client.conf file
  template:
    src: openvpn_client.conf.j2
    dest: "{{ openvpn_client_dir }}/client.conf"
    mode: 0640
    owner: root
    group: root

- name: Create onetimesecret config
  copy:
    dest: "{{ openvpn_client_dir }}/onetimesecret.token"
    content: "{{ onetimesecret_token }}"
    mode: 0600
    owner: root
    group: root

- name: Copy make_vpn_user.sh script
  template:
    src: make_vpn_user.sh.j2
    dest: "{{ openvpn_client_dir }}/make_vpn_user.sh"
    mode: 0700
    owner: root
    group: root

- name: Check VPN-clients
  stat:
    path: "{{ openvpn_client_dir }}/{{ item.username }}/{{ openvpn_name }}.ovpn"
  register: stat_vpn_clients
  with_items: "{{ openvpn_clients }}"

- name: Create VPN-clients
  shell: "{{ openvpn_client_dir }}/make_vpn_user.sh {{ item.item.username }} {{ item.item.email | default('') }}"
  when: not item.stat.exists or openvpn_force_clients | default(false) | bool
  with_items: "{{ stat_vpn_clients.results }}"
