---
# Should be on dedicated CA host

- name: Create config directory for certs and keys
  file:
    path: "{{ openvpn_server_dir }}"
    state: directory
    mode: 0755

# [On all hosts]
- name: Check if Easy RSA directory exists
  stat:
    path: "{{ easyrsa_directory }}"
  register: easydir

# [On all hosts]
- name: Copy Easy RSA
  shell: cp -r /usr/share/easy-rsa "{{ easyrsa_directory }}"
  when: easydir.stat.exists == False

# [On all hosts]
- name: Copy Easy RSA vars file
  template:
    src: easyrsa_vars.j2
    dest: "{{ easyrsa_directory }}/vars"
    mode: 0640
    owner: root
    group: root

# [On dedicated CA node]
- name: Check if Easy RSA keys directory exists
  stat:
    path: "{{ easyrsa_directory }}/keys"
  register: easykeysdir

# [On dedicated CA node]
- name: Create public key infrastructure and root CA cert
  shell: |
    ./easyrsa init-pki && \
    dd if=/dev/urandom of=pki/.rnd bs=256 count=1 && \
    ./easyrsa build-ca nopass
  args:
    executable: /bin/bash
    chdir: "{{ easyrsa_directory }}"
  when: easykeysdir.stat.exists == False
  register: easyrsaconfig

- name: Check request
  stat:
    path: "{{ easyrsa_directory }}/pki/private/{{ ansible_hostname }}.key"
  register: easyrsarequest

# With dedicated CA add:
# ./easyrsa init-pki
- name: Generate request
  shell: ./easyrsa gen-req {{ ansible_hostname }} nopass
  args:
    executable: /bin/bash
    chdir: "{{ easyrsa_directory }}"
  when: easyrsarequest.stat.exists == False

- name: Copy server cert key to config
  copy:
    remote_src: yes
    src: "{{ easyrsa_directory }}/pki/private/{{ ansible_hostname }}.key"
    dest: "{{ openvpn_server_dir }}/{{ ansible_hostname }}.key"
    owner: root
    group: root
    mode: 0640

# [On dedicated CA node]
- name: Check signed server cert
  stat:
    path: "{{ easyrsa_directory }}/pki/issued/{{ ansible_hostname }}.crt"
  register: easyrsasigned

# [On dedicated CA node]
# With dedicated CA add:
# ./easyrsa import-req pki/reqs/{{ ansible_hostname }}.req {{ ansible_hostname }}
- name: Sign request and get server cert
  shell: ./easyrsa sign-req server {{ ansible_hostname }}
  args:
    executable: /bin/bash
    chdir: "{{ easyrsa_directory }}"
  when: easyrsasigned.stat.exists == False

- name: Copy signed server cert and CA cert to config
  copy:
    remote_src: yes
    src: "{{ item }}"
    dest: "{{ openvpn_server_dir }}"
    owner: root
    group: root
    mode: 0640
  with_items:
    - "{{ easyrsa_directory }}/pki/issued/{{ ansible_hostname }}.crt"
    - "{{ easyrsa_directory }}/pki/ca.crt"

- name: Check HMAC sign
  stat:
    path: "{{ easyrsa_directory }}/ta.key"
  register: easyrsahmac

- name: Create HMAC sign (may take a while)
  shell: openvpn --genkey --secret ta.key
  args:
    executable: /bin/bash
    chdir: "{{ easyrsa_directory }}/pki"
  when: easyrsahmac.stat.exists == False

- name: Copy HMAC sign to config
  copy:
    remote_src: yes
    src: "{{ easyrsa_directory }}/pki/ta.key"
    dest: "{{ openvpn_server_dir }}"
    owner: root
    group: root
    mode: 0640

# - name: Modify pkitool to allow passout client password
#   replace:
#     dest: "{{ easyrsa_directory }}/pkitool"
#     regexp: 'NODES_REQ=""'
#     replace: 'NODES_REQ="-passout env:KEY_PASSWORD"'
#     backup: yes

# - name: Check if Easy RSA client certificate exists
#   stat:
#     path: "{{ easyrsa_directory }}/keys/{{ item.username }}.key"
#   register: easyclient
#   when: item != ""
#   with_items: "{{ openvpn_clients }}"

# - name: Create Easy RSA certificate for OpenVPN client
#   shell: source ./vars && ./build-key-pass "{{ item.username }}"
#   args:
#     executable: /bin/bash
#     chdir: "{{ easyrsa_directory }}"
#   environment:
#     KEY_PASSWORD: "{{ item.password }}"
#   when: easyclient is defined and easyclient.results.stat.exists == False
#   with_items: "{{ openvpn_clients }}"

# - name: Check if Easy RSA DES3 client certificate exists
#   stat:
#     path: "{{ easyrsa_directory }}/keys/{{ item.username }}.3des.key"
#   register: easyclientdes3
#   when: item != ""
#   with_items: "{{ openvpn_clients }}"

# - name: Convert OpenVPN client key to DES3 for Android or iOS clients
#   shell: openssl rsa -in "{{ item.username }}.key" -des3 -out "{{ item.username }}.3des.key" -passin pass:$KEY_PASSWORD -passout pass:$KEY_PASSWORD
#   args:
#     executable: /bin/bash
#     chdir: "{{ easyrsa_directory }}/keys"
#   environment:
#     KEY_PASSWORD: "{{ item.password }}"
#   when: easyclientdes3 is defined and easyclientdes3.results.stat.exists == False 
#   with_items: "{{ openvpn_clients }}"

# - name: Check if Easy RSA DH pem exists
#   stat:
#     path: "{{ easyrsa_directory }}/keys/dh{{ easyrsa_key_size }}.pem"
#   register: easydh

# - name: Build Easy RSA DH (will take a while)
#   shell: source ./vars && ./build-dh
#   args:
#     executable: /bin/bash
#     chdir: "{{ easyrsa_directory }}"
#   async: 5000
#   poll: 30
#   notify: restart openvpn
#   when: easydh.stat.exists == False
